### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb

### ISSUE THREAD

**Issue by kurtlebreton** [martin68/apt-smart#5]
I stumbled onto apt-smart while attempting to find solutions to the common "hash sum mismatch" problem with apt-get.

I installed as per instructions and then ran `apt-smart -b` as can be seen in the below output. However the below error was encountered.

The second time I ran it succeeded and reported mirror `http://mirror.solnode.io/ubuntu/releases`.

However the third and all subsequent attempts failed with the below error although with different ordinal positions eg `byte 0x8d in position 46457`, `byte 0xe6 in position 53352`, `byte 0xb0 in position 15208`.

Scripts are being run in Ubuntu 18.04 using Vagrant with VirtualBox hosted in Win10.

```
vagrant@vagrant:~$ which apt-smart
/home/vagrant/.local/bin/apt-smart
vagrant@vagrant:~$ apt-smart -b
2020-05-02 01:55:08 vagrant apt_smart[17170] INFO Ubuntu 18.04 (bionic) is supported (based on known EOL dates).
2020-05-02 01:55:08 vagrant apt_smart[17170] INFO Adding BASE_URL mirror:
2020-05-02 01:55:08 vagrant apt_smart[17170] INFO http://archive.ubuntu.com/ubuntu
2020-05-02 01:55:08 vagrant apt_smart.backends.ubuntu[17170] INFO Identifying fast Ubuntu mirrors using http://mirrors.ubuntu.com/mirrors.txt ..
2020-05-02 01:55:09 vagrant apt_smart.backends.ubuntu[17170] INFO Discovered 18 Ubuntu mirrors in 1.22 second.
2020-05-02 01:55:09 vagrant apt_smart[17170] INFO Checking 18 mirrors for availability and performance ..
2020-05-02 01:55:14 vagrant apt_smart[17170] INFO Start retrieving :attr:`base_last_updated` using is_available
2020-05-02 01:55:14 vagrant apt_smart.cli[17170] ERROR Encountered unexpected exception! Aborting ..
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/apt_smart/cli.py", line 211, in main
    callback()
  File "/home/vagrant/.local/lib/python2.7/site-packages/apt_smart/cli.py", line 224, in report_best_mirror
    output(updater.best_mirror)
  File "/home/vagrant/.local/lib/python2.7/site-packages/property_manager/__init__.py", line 788, in __get__
    value = super(custom_property, self).__get__(obj, type)
  File "/home/vagrant/.local/lib/python2.7/site-packages/apt_smart/__init__.py", line 208, in best_mirror
    return self.ranked_mirrors[0].mirror_url
  File "/home/vagrant/.local/lib/python2.7/site-packages/property_manager/__init__.py", line 788, in __get__
    value = super(custom_property, self).__get__(obj, type)
  File "/home/vagrant/.local/lib/python2.7/site-packages/apt_smart/__init__.py", line 422, in ranked_mirrors
    update_mapping = dict((c.archive_update_in_progress_url, c) for c in mirrors if c.is_available)
  File "/home/vagrant/.local/lib/python2.7/site-packages/apt_smart/__init__.py", line 422, in <genexpr>
    update_mapping = dict((c.archive_update_in_progress_url, c) for c in mirrors if c.is_available)
  File "/home/vagrant/.local/lib/python2.7/site-packages/property_manager/__init__.py", line 788, in __get__
    value = super(custom_property, self).__get__(obj, type)
  File "/home/vagrant/.local/lib/python2.7/site-packages/apt_smart/__init__.py", line 1045, in is_available
    date_string_raw = self.release_gpg_contents.decode().split("Date: ", 1)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 36813: ordinal not in range(128)
```

**Comment by martin68** [comment]
@kurtlebreton  Sorry for late fix, I've released new version 7.1.3, pls update & test. I'm closing this issue, pls reopen it if you find any related problem. THX!
